server:
  port: 8087
  servlet:
    context-path: /springboot-conformity-multipartfile

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB

# ftp服务器配置      
ftp:
  fileUrl: http://www.hejianliang.info:20082/
  host: www.hejianliang.info
  userName: xxxxx
  password: xxxxx
  port: 20022
  rootPath: /usr/local/src/filedata
      