server:
  port: 8087
  servlet:
    context-path: /springboot-conformity-multipartfile

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB

# ftp服务器配置      
ftp:
  fileUrl: http://www.hejianliang.info:20082/
  host: www.hejianliang.info
  userName: root
  password: 392a32ea72d6bcba621e0e36be46cba0
  port: 22
  rootPath: /usr/local/src/filedata
      