server:
  port: 8097
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.158.120:33306/easyexcel?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Master555_
  # springdatajpa
  # 打印出自动生成的SQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 指定生成表名的存储引擎为InneoDB
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect    