server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/practice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    map-underscore-to-camel-case: true
    use-column-label: true