server:
  port: 8090

jasypt:
  encryptor:
    password: 6c5405e9-da58-46b0-91af-605d72e8569c
    
# 邮箱服务器地址
spring:
  mail:
    host: smtp.qq.com
    username: 
    password: 
    default-encoding: UTF-8