server:
  port: 8092
  
spring:
  activemq:
    broker-url: tcp://139.196.158.120:61616
    user: admin
    password: admin
    close-timeout: 15s # 在考虑结束之前等待的时间
    in-memory: true # 默认代理URL是否应该在内存中。如果指定了显示代理，则忽略此值
    non-blocking-redelivery: false # 是否在回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会保留
    send-timeout: 0 # 等待消息发送响应的时间。设置0为等待永远
    queue-name: springboot-conformity-activemq-producer-queue
    topic-name: springboot-conformity-activemq-producer-topic
  pool:
    enabled: true
    max-connections: 10 # 连接池最大连接数
    idle-timeout: 30000 # 空闲的连接过期时间，默认为30秒
